### ISSUE TITLE
Login screen not open

### ISSUE THREAD

**Issue by Nagendrababu61** [Microsoft/SmartHotel360-mobile-desktop-apps#13]
![screenshot_20180102-022822](https://user-images.githubusercontent.com/22348157/34471107-64d2d708-ef65-11e7-8fb6-d4115b930d34.png)
Hi, I got issue in Alcatel a10 tab login screen not coming properly, just I share the screen shot, suggest me where I made mistake while compiling code.
![screenshot_20180102-022822](https://user-images.githubusercontent.com/22348157/34471097-4d9375e8-ef65-11e7-8e59-9602a6fe9979.png)

**Comment by gordingin** [comment]
I have the same issue.

**Comment by MihaMarkic** [comment]
Stating the Android version would be useful.

**Comment by jsuarezruiz** [comment]
I have done tests on different Android tablet devices. Effectively it looks like in the previous screenshoots.
There was a problem related to the use of **OnIdiom** and the lack of values for Tablet. The error has been fixed with the PR https://github.com/Microsoft/SmartHotel360-mobile-desktop-apps/pull/14

![image](https://user-images.githubusercontent.com/6755973/34716583-914283a8-f530-11e7-8722-e979af9d055f.png)

**Comment by jsuarezruiz** [comment]
The PR has been merged. Can you try again?

**Comment by Nagendrababu61** [comment]
Thank you, Now it is working fine..

**Comment by EmilAlipiev** [comment]
@jsuarezruiz  how can we run this app local without registering? it is set to  AppSettings.UseFakes = true;
but what to do after it? is there usage guide?
